config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
 # validates :name, :description, :address, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
 before_action :set_flat, only: [:show, :edit, :update, :destroy]

 def index
  @flats = Flat.all
 end

 def show
 end

 def new
  @flat = Flat.new
 end

 def create
  @flat = Flat.new(flat_params)
  @flat.save
  redirect_to flat_path(@flat)
 end

 def edit
 end

 def update
  @flat.update(flat_params)
  redirect_to flat_path(@flat)
 end

 def destroy
  @flat.destroy
  redirect_to flats_path
 end

 private

 def set_flat
  @flat = Flat.find(params[:id])
 end

 def flat_params
  params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests, type: 'select', collection: 0..10 %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
<h1>Edit a flat</h1>
<%= render 'form' %>

 <div class="link-container mt-2">
   <a class="btn btn-primary" href="/flats" role="button">Home</a>
 </div>
</div>

app/views/flats/index.html.erb
<div class="container">
 <h1>All our Flats</h1>
 <div class="card-deck">
  <% @flats.each do |flat| %>
   <div class="card-body m-2 p-0 rounded">
    <div class="incard p-1">
     <h3><%= flat.name  %></h3>
     <p><%= flat.address  %></p>
     <div class="options">
      <p><i class="fas fa-user-friends"></i> <%= flat.number_of_guests  %></p>
      <p><i class="fas fa-euro-sign ml-2"></i> <%= flat.price_per_night  %></p>
     </div>
    </div>
    <div class="more-info p-2">
     <%= link_to  "More info", flat_path(flat), class: 'text-info' %>
     <%= link_to  "Edit", edit_flat_path(flat), class: 'text-warning' %>
     <%= link_to 'Delete', flat_path(flat),
         method: :delete,
         data: { confirm: 'Are you sure?' },
         class: 'text-danger' %>
    </div>
   </div>
  <% end %>
 </div>

</div>

app/views/flats/new.html.erb
<div class="container">
<h1>Create a flat</h1>
<%= render 'form' %>

 <div class="link-container mt-2">
   <a class="btn btn-primary" href="/flats" role="button">Home</a>
 </div>
</div>

app/views/flats/show.html.erb
<div class="container">

 <div class="info">
  <h2><%= @flat.name  %></h1>
   <p><%= @flat.address  %></p>
 </div>

 <div class="info">
  <h2>A little bit more about this flat</h2>
  <p><%= @flat.description  %></p>
 </div>

 <div class="info">
  <h2>Details</h2>
  <div class="options">
   <p><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests  %></p>
   <p><i class="fas fa-euro-sign ml-2"></i> <%= @flat.price_per_night  %></p>
  </div>
 </div>

 <div class="link-container mt-2">
  <a class="btn btn-primary" href="/flats" role="button">Home</a>
  <%= link_to  "Edit", edit_flat_path(@flat), class: 'btn btn-primary' %>
       <%= link_to 'Delete', flat_path(@flat),
         method: :delete,
         data: { confirm: 'Are you sure?' },
         class: 'btn btn-primary' %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/flats">
        <img src="https://cdn.freelogovectors.net/wp-content/uploads/2016/12/airbnb_logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Airbnb
      </a>
      <a href="/flats/new" class='btn btn-sm btn-outline-secondary'>Add a flat</a>
    </nav>
    <%= yield %>
  </body>
</html>